/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type ValidatorInfoStruct = { signer: AddressLike; power: BigNumberish };

export type ValidatorInfoStructOutput = [signer: string, power: bigint] & {
  signer: string;
  power: bigint;
};

export type WithdrawActionStruct = {
  token: AddressLike;
  amount: BigNumberish;
  fee: BigNumberish;
  receiver: AddressLike;
};

export type WithdrawActionStructOutput = [
  token: string,
  amount: bigint,
  fee: bigint,
  receiver: string
] & { token: string; amount: bigint; fee: bigint; receiver: string };

export interface AssetVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "PAUSE_ROLE"
      | "TOKEN_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "UPGRADE_ROLE"
      | "addToken"
      | "addValidators"
      | "availableValidators"
      | "batchFlushWithdrawals"
      | "batchResetWithdrawHotAmount"
      | "batchTogglePendingWithdrawal"
      | "executePendingWithdrawal"
      | "fees"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "pause"
      | "paused"
      | "pendingWithdrawChallengePeriod"
      | "pendingWithdrawalIds"
      | "proxiableUUID"
      | "removeToken"
      | "removeValidators"
      | "renounceRole"
      | "requestWithdraw"
      | "revokeRole"
      | "supportedTokens"
      | "supportsInterface"
      | "unpause"
      | "updatePendingWithdrawChallengePeriod"
      | "updateToken"
      | "upgradeToAndCall"
      | "withdrawFees"
      | "withdrawals"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositETH"
      | "FeesWithdrawn"
      | "Initialized"
      | "Paused"
      | "PendingWithdrawChallengePeriodUpdated"
      | "PendingWithdrawalToggled"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TokenAdded"
      | "TokenRemoved"
      | "TokenUpdated"
      | "Unpaused"
      | "Upgraded"
      | "ValidatorsAdded"
      | "ValidatorsRemoved"
      | "WithdrawExecuted"
      | "WithdrawHotAmountRefilled"
      | "WithdrawHotAmountUsed"
      | "WithdrawalAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToken",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidators",
    values: [ValidatorInfoStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "availableValidators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchFlushWithdrawals",
    values: [BigNumberish[], ValidatorInfoStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchResetWithdrawHotAmount",
    values: [AddressLike[], ValidatorInfoStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTogglePendingWithdrawal",
    values: [BigNumberish[], boolean, ValidatorInfoStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executePendingWithdrawal",
    values: [BigNumberish, ValidatorInfoStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "fees", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawChallengePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawalIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidators",
    values: [ValidatorInfoStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values: [
      BigNumberish,
      boolean,
      ValidatorInfoStruct[],
      WithdrawActionStruct,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePendingWithdrawChallengePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateToken",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawals",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PAUSE_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TOKEN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchFlushWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchResetWithdrawHotAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTogglePendingWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePendingWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawChallengePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawalIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePendingWithdrawChallengePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawals",
    data: BytesLike
  ): Result;
}

export namespace DepositETHEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike];
  export type OutputTuple = [to: string];
  export interface OutputObject {
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingWithdrawChallengePeriodUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingWithdrawalToggledEvent {
  export type InputTuple = [id: BigNumberish, paused: boolean];
  export type OutputTuple = [id: bigint, paused: boolean];
  export interface OutputObject {
    id: bigint;
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAddedEvent {
  export type InputTuple = [
    token: AddressLike,
    hardCapRatioBps: BigNumberish,
    refillRateMps: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    hardCapRatioBps: bigint,
    refillRateMps: bigint
  ];
  export interface OutputObject {
    token: string;
    hardCapRatioBps: bigint;
    refillRateMps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRemovedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    hardCapRatioBps: BigNumberish,
    refillRateMps: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    hardCapRatioBps: bigint,
    refillRateMps: bigint
  ];
  export interface OutputObject {
    token: string;
    hardCapRatioBps: bigint;
    refillRateMps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorsAddedEvent {
  export type InputTuple = [
    hash: BytesLike,
    count: BigNumberish,
    totalPower: BigNumberish
  ];
  export type OutputTuple = [hash: string, count: bigint, totalPower: bigint];
  export interface OutputObject {
    hash: string;
    count: bigint;
    totalPower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorsRemovedEvent {
  export type InputTuple = [hash: BytesLike, count: BigNumberish];
  export type OutputTuple = [hash: string, count: bigint];
  export interface OutputObject {
    hash: string;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawExecutedEvent {
  export type InputTuple = [
    id: BigNumberish,
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    isPending: boolean,
    isFlushed: boolean,
    isPaused: boolean
  ];
  export type OutputTuple = [
    id: bigint,
    to: string,
    token: string,
    amount: bigint,
    fee: bigint,
    isPending: boolean,
    isFlushed: boolean,
    isPaused: boolean
  ];
  export interface OutputObject {
    id: bigint;
    to: string;
    token: string;
    amount: bigint;
    fee: bigint;
    isPending: boolean;
    isFlushed: boolean;
    isPaused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawHotAmountRefilledEvent {
  export type InputTuple = [
    token: AddressLike,
    refillAmount: BigNumberish,
    usedWithdrawHotAmount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    refillAmount: bigint,
    usedWithdrawHotAmount: bigint
  ];
  export interface OutputObject {
    token: string;
    refillAmount: bigint;
    usedWithdrawHotAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawHotAmountUsedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    updateUsedWithdrawHotAmount: BigNumberish,
    forcePending: boolean
  ];
  export type OutputTuple = [
    token: string,
    amount: bigint,
    updateUsedWithdrawHotAmount: bigint,
    forcePending: boolean
  ];
  export interface OutputObject {
    token: string;
    amount: bigint;
    updateUsedWithdrawHotAmount: bigint;
    forcePending: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    receiver: AddressLike,
    isPending: boolean,
    isForcePending: boolean
  ];
  export type OutputTuple = [
    id: bigint,
    token: string,
    amount: bigint,
    fee: bigint,
    receiver: string,
    isPending: boolean,
    isForcePending: boolean
  ];
  export interface OutputObject {
    id: bigint;
    token: string;
    amount: bigint;
    fee: bigint;
    receiver: string;
    isPending: boolean;
    isForcePending: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetVault extends BaseContract {
  connect(runner?: ContractRunner | null): AssetVault;
  waitForDeployment(): Promise<this>;

  interface: AssetVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSE_ROLE: TypedContractMethod<[], [string], "view">;

  TOKEN_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  UPGRADE_ROLE: TypedContractMethod<[], [string], "view">;

  addToken: TypedContractMethod<
    [
      token: AddressLike,
      hardCapRatioBps: BigNumberish,
      refillRateMps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addValidators: TypedContractMethod<
    [validators: ValidatorInfoStruct[]],
    [void],
    "nonpayable"
  >;

  availableValidators: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  batchFlushWithdrawals: TypedContractMethod<
    [
      ids: BigNumberish[],
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  batchResetWithdrawHotAmount: TypedContractMethod<
    [
      tokens: AddressLike[],
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  batchTogglePendingWithdrawal: TypedContractMethod<
    [
      ids: BigNumberish[],
      shouldPause: boolean,
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  executePendingWithdrawal: TypedContractMethod<
    [
      id: BigNumberish,
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  fees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_pendingWithdrawChallengePeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingWithdrawChallengePeriod: TypedContractMethod<[], [bigint], "view">;

  pendingWithdrawalIds: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeToken: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  removeValidators: TypedContractMethod<
    [validators: ValidatorInfoStruct[]],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestWithdraw: TypedContractMethod<
    [
      id: BigNumberish,
      isForcePending: boolean,
      validators: ValidatorInfoStruct[],
      action: WithdrawActionStruct,
      validatorSignatures: BytesLike[]
    ],
    [void],
    "payable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        token: string;
        hardCapRatioBps: bigint;
        refillRateMps: bigint;
        lastRefillTimestamp: bigint;
        usedWithdrawHotAmount: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updatePendingWithdrawChallengePeriod: TypedContractMethod<
    [newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateToken: TypedContractMethod<
    [
      token: AddressLike,
      hardCapRatioBps: BigNumberish,
      refillRateMps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdrawFees: TypedContractMethod<
    [tokens: AddressLike[], to: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, boolean, boolean, bigint, string, bigint, string, bigint] & {
        paused: boolean;
        pending: boolean;
        executed: boolean;
        amount: bigint;
        token: string;
        fee: bigint;
        receiver: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TOKEN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      hardCapRatioBps: BigNumberish,
      refillRateMps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addValidators"
  ): TypedContractMethod<
    [validators: ValidatorInfoStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "availableValidators"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchFlushWithdrawals"
  ): TypedContractMethod<
    [
      ids: BigNumberish[],
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchResetWithdrawHotAmount"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchTogglePendingWithdrawal"
  ): TypedContractMethod<
    [
      ids: BigNumberish[],
      shouldPause: boolean,
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executePendingWithdrawal"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      validators: ValidatorInfoStruct[],
      validatorSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_pendingWithdrawChallengePeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawChallengePeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawalIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeValidators"
  ): TypedContractMethod<
    [validators: ValidatorInfoStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      isForcePending: boolean,
      validators: ValidatorInfoStruct[],
      action: WithdrawActionStruct,
      validatorSignatures: BytesLike[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        token: string;
        hardCapRatioBps: bigint;
        refillRateMps: bigint;
        lastRefillTimestamp: bigint;
        usedWithdrawHotAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePendingWithdrawChallengePeriod"
  ): TypedContractMethod<[newValue: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      hardCapRatioBps: BigNumberish,
      refillRateMps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<
    [tokens: AddressLike[], to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, boolean, boolean, bigint, string, bigint, string, bigint] & {
        paused: boolean;
        pending: boolean;
        executed: boolean;
        amount: bigint;
        token: string;
        fee: bigint;
        receiver: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DepositETH"
  ): TypedContractEvent<
    DepositETHEvent.InputTuple,
    DepositETHEvent.OutputTuple,
    DepositETHEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PendingWithdrawChallengePeriodUpdated"
  ): TypedContractEvent<
    PendingWithdrawChallengePeriodUpdatedEvent.InputTuple,
    PendingWithdrawChallengePeriodUpdatedEvent.OutputTuple,
    PendingWithdrawChallengePeriodUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PendingWithdrawalToggled"
  ): TypedContractEvent<
    PendingWithdrawalToggledEvent.InputTuple,
    PendingWithdrawalToggledEvent.OutputTuple,
    PendingWithdrawalToggledEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAdded"
  ): TypedContractEvent<
    TokenAddedEvent.InputTuple,
    TokenAddedEvent.OutputTuple,
    TokenAddedEvent.OutputObject
  >;
  getEvent(
    key: "TokenRemoved"
  ): TypedContractEvent<
    TokenRemovedEvent.InputTuple,
    TokenRemovedEvent.OutputTuple,
    TokenRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TokenUpdated"
  ): TypedContractEvent<
    TokenUpdatedEvent.InputTuple,
    TokenUpdatedEvent.OutputTuple,
    TokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorsAdded"
  ): TypedContractEvent<
    ValidatorsAddedEvent.InputTuple,
    ValidatorsAddedEvent.OutputTuple,
    ValidatorsAddedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorsRemoved"
  ): TypedContractEvent<
    ValidatorsRemovedEvent.InputTuple,
    ValidatorsRemovedEvent.OutputTuple,
    ValidatorsRemovedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawExecuted"
  ): TypedContractEvent<
    WithdrawExecutedEvent.InputTuple,
    WithdrawExecutedEvent.OutputTuple,
    WithdrawExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawHotAmountRefilled"
  ): TypedContractEvent<
    WithdrawHotAmountRefilledEvent.InputTuple,
    WithdrawHotAmountRefilledEvent.OutputTuple,
    WithdrawHotAmountRefilledEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawHotAmountUsed"
  ): TypedContractEvent<
    WithdrawHotAmountUsedEvent.InputTuple,
    WithdrawHotAmountUsedEvent.OutputTuple,
    WithdrawHotAmountUsedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalAdded"
  ): TypedContractEvent<
    WithdrawalAddedEvent.InputTuple,
    WithdrawalAddedEvent.OutputTuple,
    WithdrawalAddedEvent.OutputObject
  >;

  filters: {
    "DepositETH(address,uint256)": TypedContractEvent<
      DepositETHEvent.InputTuple,
      DepositETHEvent.OutputTuple,
      DepositETHEvent.OutputObject
    >;
    DepositETH: TypedContractEvent<
      DepositETHEvent.InputTuple,
      DepositETHEvent.OutputTuple,
      DepositETHEvent.OutputObject
    >;

    "FeesWithdrawn(address)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PendingWithdrawChallengePeriodUpdated(uint256,uint256)": TypedContractEvent<
      PendingWithdrawChallengePeriodUpdatedEvent.InputTuple,
      PendingWithdrawChallengePeriodUpdatedEvent.OutputTuple,
      PendingWithdrawChallengePeriodUpdatedEvent.OutputObject
    >;
    PendingWithdrawChallengePeriodUpdated: TypedContractEvent<
      PendingWithdrawChallengePeriodUpdatedEvent.InputTuple,
      PendingWithdrawChallengePeriodUpdatedEvent.OutputTuple,
      PendingWithdrawChallengePeriodUpdatedEvent.OutputObject
    >;

    "PendingWithdrawalToggled(uint256,bool)": TypedContractEvent<
      PendingWithdrawalToggledEvent.InputTuple,
      PendingWithdrawalToggledEvent.OutputTuple,
      PendingWithdrawalToggledEvent.OutputObject
    >;
    PendingWithdrawalToggled: TypedContractEvent<
      PendingWithdrawalToggledEvent.InputTuple,
      PendingWithdrawalToggledEvent.OutputTuple,
      PendingWithdrawalToggledEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TokenAdded(address,uint256,uint256)": TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;
    TokenAdded: TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;

    "TokenRemoved(address)": TypedContractEvent<
      TokenRemovedEvent.InputTuple,
      TokenRemovedEvent.OutputTuple,
      TokenRemovedEvent.OutputObject
    >;
    TokenRemoved: TypedContractEvent<
      TokenRemovedEvent.InputTuple,
      TokenRemovedEvent.OutputTuple,
      TokenRemovedEvent.OutputObject
    >;

    "TokenUpdated(address,uint256,uint256)": TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;
    TokenUpdated: TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "ValidatorsAdded(bytes32,uint256,uint256)": TypedContractEvent<
      ValidatorsAddedEvent.InputTuple,
      ValidatorsAddedEvent.OutputTuple,
      ValidatorsAddedEvent.OutputObject
    >;
    ValidatorsAdded: TypedContractEvent<
      ValidatorsAddedEvent.InputTuple,
      ValidatorsAddedEvent.OutputTuple,
      ValidatorsAddedEvent.OutputObject
    >;

    "ValidatorsRemoved(bytes32,uint256)": TypedContractEvent<
      ValidatorsRemovedEvent.InputTuple,
      ValidatorsRemovedEvent.OutputTuple,
      ValidatorsRemovedEvent.OutputObject
    >;
    ValidatorsRemoved: TypedContractEvent<
      ValidatorsRemovedEvent.InputTuple,
      ValidatorsRemovedEvent.OutputTuple,
      ValidatorsRemovedEvent.OutputObject
    >;

    "WithdrawExecuted(uint256,address,address,uint256,uint256,bool,bool,bool)": TypedContractEvent<
      WithdrawExecutedEvent.InputTuple,
      WithdrawExecutedEvent.OutputTuple,
      WithdrawExecutedEvent.OutputObject
    >;
    WithdrawExecuted: TypedContractEvent<
      WithdrawExecutedEvent.InputTuple,
      WithdrawExecutedEvent.OutputTuple,
      WithdrawExecutedEvent.OutputObject
    >;

    "WithdrawHotAmountRefilled(address,uint256,uint256)": TypedContractEvent<
      WithdrawHotAmountRefilledEvent.InputTuple,
      WithdrawHotAmountRefilledEvent.OutputTuple,
      WithdrawHotAmountRefilledEvent.OutputObject
    >;
    WithdrawHotAmountRefilled: TypedContractEvent<
      WithdrawHotAmountRefilledEvent.InputTuple,
      WithdrawHotAmountRefilledEvent.OutputTuple,
      WithdrawHotAmountRefilledEvent.OutputObject
    >;

    "WithdrawHotAmountUsed(address,uint256,uint256,bool)": TypedContractEvent<
      WithdrawHotAmountUsedEvent.InputTuple,
      WithdrawHotAmountUsedEvent.OutputTuple,
      WithdrawHotAmountUsedEvent.OutputObject
    >;
    WithdrawHotAmountUsed: TypedContractEvent<
      WithdrawHotAmountUsedEvent.InputTuple,
      WithdrawHotAmountUsedEvent.OutputTuple,
      WithdrawHotAmountUsedEvent.OutputObject
    >;

    "WithdrawalAdded(uint256,address,uint256,uint256,address,bool,bool)": TypedContractEvent<
      WithdrawalAddedEvent.InputTuple,
      WithdrawalAddedEvent.OutputTuple,
      WithdrawalAddedEvent.OutputObject
    >;
    WithdrawalAdded: TypedContractEvent<
      WithdrawalAddedEvent.InputTuple,
      WithdrawalAddedEvent.OutputTuple,
      WithdrawalAddedEvent.OutputObject
    >;
  };
}
