/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type ValidatorInfoStruct = {
  signer: PromiseOrValue<string>;
  power: PromiseOrValue<BigNumberish>;
};

export type ValidatorInfoStructOutput = [string, BigNumber] & {
  signer: string;
  power: BigNumber;
};

export type WithdrawActionStruct = {
  token: PromiseOrValue<string>;
  amount: PromiseOrValue<BigNumberish>;
  fee: PromiseOrValue<BigNumberish>;
  receiver: PromiseOrValue<string>;
  withdrawType: PromiseOrValue<BigNumberish>;
};

export type WithdrawActionStructOutput = [
  string,
  BigNumber,
  BigNumber,
  string,
  number
] & {
  token: string;
  amount: BigNumber;
  fee: BigNumber;
  receiver: string;
  withdrawType: number;
};

export interface AssetVaultInterface extends utils.Interface {
  functions: {
    "ADMIN_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "OPERATOR_ROLE()": FunctionFragment;
    "PAUSE_ROLE()": FunctionFragment;
    "TOKEN_ROLE()": FunctionFragment;
    "UPGRADE_INTERFACE_VERSION()": FunctionFragment;
    "UPGRADE_ROLE()": FunctionFragment;
    "addToken(address,uint256,uint256)": FunctionFragment;
    "addValidators((address,uint256)[])": FunctionFragment;
    "availableValidators(bytes32)": FunctionFragment;
    "deposit(address,uint256)": FunctionFragment;
    "executeWithdrawal(uint256)": FunctionFragment;
    "fees(address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize(uint256)": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "pendingWithdrawChallengePeriod()": FunctionFragment;
    "pendingWithdrawalIds(uint256)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "removeToken(address)": FunctionFragment;
    "removeValidators((address,uint256)[])": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "supportedTokens(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updatePendingWithdrawChallengePeriod(uint256)": FunctionFragment;
    "updateToken(address,uint256,uint256)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "withdraw(uint256,(address,uint256)[],(address,uint256,uint256,address,uint8),bytes[])": FunctionFragment;
    "withdrawFees(address[],uint256[],address)": FunctionFragment;
    "withdrawals(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "PAUSE_ROLE"
      | "TOKEN_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "UPGRADE_ROLE"
      | "addToken"
      | "addValidators"
      | "availableValidators"
      | "deposit"
      | "executeWithdrawal"
      | "fees"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "pause"
      | "paused"
      | "pendingWithdrawChallengePeriod"
      | "pendingWithdrawalIds"
      | "proxiableUUID"
      | "removeToken"
      | "removeValidators"
      | "renounceRole"
      | "revokeRole"
      | "supportedTokens"
      | "supportsInterface"
      | "unpause"
      | "updatePendingWithdrawChallengePeriod"
      | "updateToken"
      | "upgradeToAndCall"
      | "withdraw"
      | "withdrawFees"
      | "withdrawals"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidators",
    values: [ValidatorInfoStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "availableValidators",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithdrawal",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "fees",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawChallengePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawalIds",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidators",
    values: [ValidatorInfoStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePendingWithdrawChallengePeriod",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      PromiseOrValue<BigNumberish>,
      ValidatorInfoStruct[],
      WithdrawActionStruct,
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawals",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PAUSE_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TOKEN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawChallengePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawalIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePendingWithdrawChallengePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawals",
    data: BytesLike
  ): Result;

  events: {
    "Deposit(address,address,uint256)": EventFragment;
    "FeesWithdrawn(address[],uint256[],address)": EventFragment;
    "Initialized(uint64)": EventFragment;
    "Paused(address)": EventFragment;
    "PendingWithdrawChallengePeriodUpdated(uint256,uint256)": EventFragment;
    "PendingWithdrawalToggled(uint256,bool)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "TokenAdded(address,uint256,uint256)": EventFragment;
    "TokenRemoved(address)": EventFragment;
    "TokenUpdated(address,uint256,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Upgraded(address)": EventFragment;
    "ValidatorsAdded(bytes32,uint256,uint256)": EventFragment;
    "ValidatorsRemoved(bytes32,uint256)": EventFragment;
    "WithdrawExecuted(uint256,address,address,uint256,uint256,bool,bool,bool,uint8)": EventFragment;
    "WithdrawHotAmountRefilled(address,uint256,uint256)": EventFragment;
    "WithdrawHotAmountUsed(address,uint256,uint256,bool)": EventFragment;
    "WithdrawalAdded(uint256,address,uint256,uint256,address,uint8,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeesWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PendingWithdrawChallengePeriodUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PendingWithdrawalToggled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorsAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorsRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawHotAmountRefilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawHotAmountUsed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalAdded"): EventFragment;
}

export interface DepositEventObject {
  account: string;
  token: string;
  amount: BigNumber;
}
export type DepositEvent = TypedEvent<
  [string, string, BigNumber],
  DepositEventObject
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface FeesWithdrawnEventObject {
  tokens: string[];
  amounts: BigNumber[];
  to: string;
}
export type FeesWithdrawnEvent = TypedEvent<
  [string[], BigNumber[], string],
  FeesWithdrawnEventObject
>;

export type FeesWithdrawnEventFilter = TypedEventFilter<FeesWithdrawnEvent>;

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface PendingWithdrawChallengePeriodUpdatedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PendingWithdrawChallengePeriodUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PendingWithdrawChallengePeriodUpdatedEventObject
>;

export type PendingWithdrawChallengePeriodUpdatedEventFilter =
  TypedEventFilter<PendingWithdrawChallengePeriodUpdatedEvent>;

export interface PendingWithdrawalToggledEventObject {
  id: BigNumber;
  paused: boolean;
}
export type PendingWithdrawalToggledEvent = TypedEvent<
  [BigNumber, boolean],
  PendingWithdrawalToggledEventObject
>;

export type PendingWithdrawalToggledEventFilter =
  TypedEventFilter<PendingWithdrawalToggledEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface TokenAddedEventObject {
  token: string;
  hardCapRatioBps: BigNumber;
  refillRateMps: BigNumber;
}
export type TokenAddedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokenAddedEventObject
>;

export type TokenAddedEventFilter = TypedEventFilter<TokenAddedEvent>;

export interface TokenRemovedEventObject {
  token: string;
}
export type TokenRemovedEvent = TypedEvent<[string], TokenRemovedEventObject>;

export type TokenRemovedEventFilter = TypedEventFilter<TokenRemovedEvent>;

export interface TokenUpdatedEventObject {
  token: string;
  hardCapRatioBps: BigNumber;
  refillRateMps: BigNumber;
}
export type TokenUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokenUpdatedEventObject
>;

export type TokenUpdatedEventFilter = TypedEventFilter<TokenUpdatedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface ValidatorsAddedEventObject {
  hash: string;
  count: BigNumber;
  totalPower: BigNumber;
}
export type ValidatorsAddedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ValidatorsAddedEventObject
>;

export type ValidatorsAddedEventFilter = TypedEventFilter<ValidatorsAddedEvent>;

export interface ValidatorsRemovedEventObject {
  hash: string;
  count: BigNumber;
}
export type ValidatorsRemovedEvent = TypedEvent<
  [string, BigNumber],
  ValidatorsRemovedEventObject
>;

export type ValidatorsRemovedEventFilter =
  TypedEventFilter<ValidatorsRemovedEvent>;

export interface WithdrawExecutedEventObject {
  id: BigNumber;
  to: string;
  token: string;
  amount: BigNumber;
  fee: BigNumber;
  isPending: boolean;
  isFlushed: boolean;
  isPaused: boolean;
  withdrawType: number;
}
export type WithdrawExecutedEvent = TypedEvent<
  [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    boolean,
    boolean,
    number
  ],
  WithdrawExecutedEventObject
>;

export type WithdrawExecutedEventFilter =
  TypedEventFilter<WithdrawExecutedEvent>;

export interface WithdrawHotAmountRefilledEventObject {
  token: string;
  refillAmount: BigNumber;
  usedWithdrawHotAmount: BigNumber;
}
export type WithdrawHotAmountRefilledEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  WithdrawHotAmountRefilledEventObject
>;

export type WithdrawHotAmountRefilledEventFilter =
  TypedEventFilter<WithdrawHotAmountRefilledEvent>;

export interface WithdrawHotAmountUsedEventObject {
  token: string;
  amount: BigNumber;
  updateUsedWithdrawHotAmount: BigNumber;
  forcePending: boolean;
}
export type WithdrawHotAmountUsedEvent = TypedEvent<
  [string, BigNumber, BigNumber, boolean],
  WithdrawHotAmountUsedEventObject
>;

export type WithdrawHotAmountUsedEventFilter =
  TypedEventFilter<WithdrawHotAmountUsedEvent>;

export interface WithdrawalAddedEventObject {
  id: BigNumber;
  token: string;
  amount: BigNumber;
  fee: BigNumber;
  receiver: string;
  withdrawType: number;
  isPending: boolean;
}
export type WithdrawalAddedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, number, boolean],
  WithdrawalAddedEventObject
>;

export type WithdrawalAddedEventFilter = TypedEventFilter<WithdrawalAddedEvent>;

export interface AssetVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AssetVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<[string]>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    addToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addValidators(
      validators: ValidatorInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    availableValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deposit(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeWithdrawal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      _pendingWithdrawChallengePeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pendingWithdrawChallengePeriod(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pendingWithdrawalIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeValidators(
      validators: ValidatorInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        token: string;
        hardCapRatioBps: BigNumber;
        refillRateMps: BigNumber;
        lastRefillTimestamp: BigNumber;
        usedWithdrawHotAmount: BigNumber;
      }
    >;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePendingWithdrawChallengePeriod(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      id: PromiseOrValue<BigNumberish>,
      validators: ValidatorInfoStruct[],
      action: WithdrawActionStruct,
      validatorSignatures: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFees(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        boolean,
        BigNumber,
        string,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        paused: boolean;
        pending: boolean;
        executed: boolean;
        amount: BigNumber;
        token: string;
        fee: BigNumber;
        receiver: string;
        timestamp: BigNumber;
        withdrawType: number;
      }
    >;
  };

  ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  PAUSE_ROLE(overrides?: CallOverrides): Promise<string>;

  TOKEN_ROLE(overrides?: CallOverrides): Promise<string>;

  UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

  UPGRADE_ROLE(overrides?: CallOverrides): Promise<string>;

  addToken(
    token: PromiseOrValue<string>,
    hardCapRatioBps: PromiseOrValue<BigNumberish>,
    refillRateMps: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addValidators(
    validators: ValidatorInfoStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  availableValidators(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deposit(
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeWithdrawal(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fees(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _pendingWithdrawChallengePeriod: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pendingWithdrawChallengePeriod(overrides?: CallOverrides): Promise<BigNumber>;

  pendingWithdrawalIds(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  removeToken(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeValidators(
    validators: ValidatorInfoStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    callerConfirmation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportedTokens(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      token: string;
      hardCapRatioBps: BigNumber;
      refillRateMps: BigNumber;
      lastRefillTimestamp: BigNumber;
      usedWithdrawHotAmount: BigNumber;
    }
  >;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updatePendingWithdrawChallengePeriod(
    newValue: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateToken(
    token: PromiseOrValue<string>,
    hardCapRatioBps: PromiseOrValue<BigNumberish>,
    refillRateMps: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    id: PromiseOrValue<BigNumberish>,
    validators: ValidatorInfoStruct[],
    action: WithdrawActionStruct,
    validatorSignatures: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFees(
    tokens: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawals(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      boolean,
      boolean,
      BigNumber,
      string,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      paused: boolean;
      pending: boolean;
      executed: boolean;
      amount: BigNumber;
      token: string;
      fee: BigNumber;
      receiver: string;
      timestamp: BigNumber;
      withdrawType: number;
    }
  >;

  callStatic: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<string>;

    TOKEN_ROLE(overrides?: CallOverrides): Promise<string>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<string>;

    addToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    addValidators(
      validators: ValidatorInfoStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    availableValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeWithdrawal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    fees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _pendingWithdrawChallengePeriod: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pendingWithdrawChallengePeriod(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingWithdrawalIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeValidators(
      validators: ValidatorInfoStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        token: string;
        hardCapRatioBps: BigNumber;
        refillRateMps: BigNumber;
        lastRefillTimestamp: BigNumber;
        usedWithdrawHotAmount: BigNumber;
      }
    >;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updatePendingWithdrawChallengePeriod(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      id: PromiseOrValue<BigNumberish>,
      validators: ValidatorInfoStruct[],
      action: WithdrawActionStruct,
      validatorSignatures: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFees(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        boolean,
        BigNumber,
        string,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        paused: boolean;
        pending: boolean;
        executed: boolean;
        amount: BigNumber;
        token: string;
        fee: BigNumber;
        receiver: string;
        timestamp: BigNumber;
        withdrawType: number;
      }
    >;
  };

  filters: {
    "Deposit(address,address,uint256)"(
      account?: null,
      token?: null,
      amount?: null
    ): DepositEventFilter;
    Deposit(account?: null, token?: null, amount?: null): DepositEventFilter;

    "FeesWithdrawn(address[],uint256[],address)"(
      tokens?: null,
      amounts?: null,
      to?: null
    ): FeesWithdrawnEventFilter;
    FeesWithdrawn(
      tokens?: null,
      amounts?: null,
      to?: null
    ): FeesWithdrawnEventFilter;

    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "PendingWithdrawChallengePeriodUpdated(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PendingWithdrawChallengePeriodUpdatedEventFilter;
    PendingWithdrawChallengePeriodUpdated(
      oldValue?: null,
      newValue?: null
    ): PendingWithdrawChallengePeriodUpdatedEventFilter;

    "PendingWithdrawalToggled(uint256,bool)"(
      id?: null,
      paused?: null
    ): PendingWithdrawalToggledEventFilter;
    PendingWithdrawalToggled(
      id?: null,
      paused?: null
    ): PendingWithdrawalToggledEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "TokenAdded(address,uint256,uint256)"(
      token?: null,
      hardCapRatioBps?: null,
      refillRateMps?: null
    ): TokenAddedEventFilter;
    TokenAdded(
      token?: null,
      hardCapRatioBps?: null,
      refillRateMps?: null
    ): TokenAddedEventFilter;

    "TokenRemoved(address)"(token?: null): TokenRemovedEventFilter;
    TokenRemoved(token?: null): TokenRemovedEventFilter;

    "TokenUpdated(address,uint256,uint256)"(
      token?: null,
      hardCapRatioBps?: null,
      refillRateMps?: null
    ): TokenUpdatedEventFilter;
    TokenUpdated(
      token?: null,
      hardCapRatioBps?: null,
      refillRateMps?: null
    ): TokenUpdatedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;

    "ValidatorsAdded(bytes32,uint256,uint256)"(
      hash?: null,
      count?: null,
      totalPower?: null
    ): ValidatorsAddedEventFilter;
    ValidatorsAdded(
      hash?: null,
      count?: null,
      totalPower?: null
    ): ValidatorsAddedEventFilter;

    "ValidatorsRemoved(bytes32,uint256)"(
      hash?: null,
      count?: null
    ): ValidatorsRemovedEventFilter;
    ValidatorsRemoved(hash?: null, count?: null): ValidatorsRemovedEventFilter;

    "WithdrawExecuted(uint256,address,address,uint256,uint256,bool,bool,bool,uint8)"(
      id?: null,
      to?: null,
      token?: null,
      amount?: null,
      fee?: null,
      isPending?: null,
      isFlushed?: null,
      isPaused?: null,
      withdrawType?: null
    ): WithdrawExecutedEventFilter;
    WithdrawExecuted(
      id?: null,
      to?: null,
      token?: null,
      amount?: null,
      fee?: null,
      isPending?: null,
      isFlushed?: null,
      isPaused?: null,
      withdrawType?: null
    ): WithdrawExecutedEventFilter;

    "WithdrawHotAmountRefilled(address,uint256,uint256)"(
      token?: null,
      refillAmount?: null,
      usedWithdrawHotAmount?: null
    ): WithdrawHotAmountRefilledEventFilter;
    WithdrawHotAmountRefilled(
      token?: null,
      refillAmount?: null,
      usedWithdrawHotAmount?: null
    ): WithdrawHotAmountRefilledEventFilter;

    "WithdrawHotAmountUsed(address,uint256,uint256,bool)"(
      token?: null,
      amount?: null,
      updateUsedWithdrawHotAmount?: null,
      forcePending?: null
    ): WithdrawHotAmountUsedEventFilter;
    WithdrawHotAmountUsed(
      token?: null,
      amount?: null,
      updateUsedWithdrawHotAmount?: null,
      forcePending?: null
    ): WithdrawHotAmountUsedEventFilter;

    "WithdrawalAdded(uint256,address,uint256,uint256,address,uint8,bool)"(
      id?: null,
      token?: null,
      amount?: null,
      fee?: null,
      receiver?: null,
      withdrawType?: null,
      isPending?: null
    ): WithdrawalAddedEventFilter;
    WithdrawalAdded(
      id?: null,
      token?: null,
      amount?: null,
      fee?: null,
      receiver?: null,
      withdrawType?: null,
      isPending?: null
    ): WithdrawalAddedEventFilter;
  };

  estimateGas: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    addToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addValidators(
      validators: ValidatorInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    availableValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeWithdrawal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _pendingWithdrawChallengePeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pendingWithdrawChallengePeriod(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingWithdrawalIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeValidators(
      validators: ValidatorInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updatePendingWithdrawChallengePeriod(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(
      id: PromiseOrValue<BigNumberish>,
      validators: ValidatorInfoStruct[],
      action: WithdrawActionStruct,
      validatorSignatures: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFees(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOKEN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UPGRADE_INTERFACE_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addValidators(
      validators: ValidatorInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    availableValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeWithdrawal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _pendingWithdrawChallengePeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingWithdrawChallengePeriod(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingWithdrawalIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeValidators(
      validators: ValidatorInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePendingWithdrawChallengePeriod(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateToken(
      token: PromiseOrValue<string>,
      hardCapRatioBps: PromiseOrValue<BigNumberish>,
      refillRateMps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      id: PromiseOrValue<BigNumberish>,
      validators: ValidatorInfoStruct[],
      action: WithdrawActionStruct,
      validatorSignatures: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFees(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
